# 生产环境配置
app:
  name: "环保数据集成平台"
  version: "1.0.0"
  environment: "production"
  debug: false

server:
  host: "0.0.0.0"
  port: 8888
  mode: "release"
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 60
  tls:
    enabled: false
    cert_file: "/app/certs/server.crt"
    key_file: "/app/certs/server.key"

database:
  driver: "mysql"
  host: "mysql"
  port: 3306
  name: "env_data_platform"
  username: "root"
  password: "Env@2024#Secure"
  charset: "utf8mb4"
  parse_time: true
  loc: "Asia%2FShanghai"
  max_idle_conns: 25
  max_open_conns: 100
  conn_max_lifetime: 3600s

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  pool_size: 50
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s

jwt:
  secret: "${JWT_SECRET:production_jwt_secret_key_please_change_this}"
  expire: 24h
  issuer: "env-data-platform"

log:
  level: "info"
  format: "json"
  output: "file"
  filename: "/app/logs/app.log"
  max_size: 100
  max_backups: 30
  max_age: 90
  compress: true

cors:
  allow_origins:
    - "*"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 12h

rate_limit:
  enabled: true
  requests_per_minute: 1000
  burst: 100

file_upload:
  max_size: 500MB
  allowed_types:
    - ".xlsx"
    - ".xls"
    - ".csv"
    - ".txt"
    - ".json"
    - ".xml"
  upload_path: "/app/uploads"

hj212:
  enabled: true
  tcp_port: 8212
  buffer_size: 8192
  timeout: 30s
  max_connections: 10000

etl:
  hop_home: "/opt/hop"
  max_concurrent_jobs: 10
  job_timeout: 7200s
  temp_path: "/app/temp/etl"

monitoring:
  enabled: true
  prometheus:
    enabled: true
    path: "/metrics"
  health_check:
    enabled: true
    path: "/health"